# Generated by Django 3.2 on 2023-09-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default='3f2f5add-53ba-48d9-99c5-997bc6894a91', verbose_name='Код подтверждения'),
        ),
    ]
