# Generated by Django 3.2 on 2023-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default='f0a57f1f-a365-4a1c-96b3-5aa81a4f7f74', verbose_name='Код подтверждения'),
        ),
    ]
